# Github Action definition for publishing to PyPI when a release is
# tagged.


name: PyPI


on:
  release:
    types: [published]


jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version:
          - '2.7'
          - '3.9'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ matrix.python-version != '2.7' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ matrix.python-version == '2.7' }}
      run: |
        sudo apt-get install -y python2

    - name: Install system packages
      run: |
        sudo apt-get install -y libssl-dev openssl swig

    - name: Install python dependencies
      run: |
        pip install wheel

    - name: Build source distribution
      if: ${{ matrix.python-version != '2.7' }}
      run: |
        python setup.py sdist --output dist

    - name: Build binary wheel distribution
      run: |
        python setup.py bdist_wheel --output dist

    - name: Save content
      uses: actions/upload-artifact@v3
      with:
        path: dist/


  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    needs:
      - build

    environment:
      name: pypi
      url: https://pypi.org/p/javatools

    steps:
    - name: Fetch content
      uses: actions/download-artifact@v3
      with:
        path: dist/

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1


# The end.
