name: Tox

on:
  - push
  - pull_request


jobs:
  build:
    runs-on: ubuntu-20.04  # because of python 2.7

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '2.7'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system packages
      run: |
        sudo apt-get install libssl-dev openssl swig

    - name: Install python dependencies
      run: |
        pip install tox tox-gh-actions wheel

    - name: Running tox
      run: tox


# The end.
